config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :closets
  get 'closets' => 'fashion#closet'
  
  get 'your_closet' => 'closets#your_closet'
  
  get 'user_closet' => 'closets#user_closet'
  
  root 'fashion#closet'

end

app/models/closet.rb
class Closet < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    
    has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :closet
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :closets
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
    :password_confirmation, :name, :username, :birthday) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
   :password_confirmation, :current_password, :name, :username, :birthday) }
  end
end

app/controllers/closets_controller.rb
class ClosetsController < ApplicationController
  before_action :set_closet, only: [:show, :edit, :update, :destroy]

  # GET /closets
  # GET /closets.json
  def index
    @closets = Closet.all
  end

  # GET /closets/1
  # GET /closets/1.json
  def show
    @comment = Comment.new
  end

  # GET /closets/new
  def new
    @closet = Closet.new
  end

  # GET /closets/1/edit
  def edit
  end
  
  def your_closet
  end
  
  def user_closet
    @user = User.find(params:[:id])
  end

  # POST /closets
  # POST /closets.json
  def create
    @closet = Closet.new(closet_params)

    respond_to do |format|
      if @closet.save
        format.html { redirect_to @closet, notice: 'Closet was successfully created.' }
        format.json { render :show, status: :created, location: @closet }
      else
        format.html { render :new }
        format.json { render json: @closet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /closets/1
  # PATCH/PUT /closets/1.json
  def update
    respond_to do |format|
      if @closet.update(closet_params)
        format.html { redirect_to @closet, notice: 'Closet was successfully updated.' }
        format.json { render :show, status: :ok, location: @closet }
      else
        format.html { render :edit }
        format.json { render json: @closet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /closets/1
  # DELETE /closets/1.json
  def destroy
    @closet.destroy
    respond_to do |format|
      format.html { redirect_to closets_url, notice: 'Closet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_closet
      @closet = Closet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def closet_params
      params.require(:closet).permit(:thing, :user_id, :avatar)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to closet_path(id: @comment.closet_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :rating, :thing_id, :closet_id, :user_id)
    end
end

app/controllers/fashion_controller.rb
class FashionController < ApplicationController
  def closet
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/closets_helper.rb
module ClosetsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fashion_helper.rb
module FashionHelper
end

app/views/closets/_form.html.erb
<%= form_for(@closet) do |f| %>
  <% if @closet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@closet.errors.count, "error") %> prohibited this closet from being saved:</h2>

      <ul>
      <% @closet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="panel-body">
  <div class="field">
    <%= f.label "Clothing Item" %><br>
    <%= f.text_field :thing %>
  </div>
  <div class="field">
    <%= f.label "Item Image" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="field cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  </div>
<% end %>

app/views/closets/edit.html.erb
<h1>Editing Closet</h1>

<%= render 'form' %>

<%= link_to 'Show', @closet %> |
<%= link_to 'Back', closets_path %>

app/views/closets/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
  <% @closets.each do |closet| %>
  <div class="container">
  <div class="col-md-6">
    <div class="panel-header">
    <h1><%= link_to closet.thing, closet %></h1>
    </div>
    <div class="panel-body">
    <p><%= image_tag closet.avatar.url(:medium) %></p>
    <p> Submitted by: <strong><%= link_to closet.user.username, user_closet_path(id: closet.user.id) %></strong></p>
    <p>
    <% if current_user.id == closet.user.id %>
    <%= link_to 'Edit', edit_closet_path(closet) %> |
    <%= link_to 'Destroy', closet, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
    </p>
  </div>
  </div>
  </div>
  <% end %>
</div>

app/views/closets/new.html.erb
<div class="container">
<h1>Enter a New Item for the Closet</h1>

<%= render 'form' %>

<p><%= link_to 'Back', closets_path %></p>
</div>

app/views/closets/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<div class="panel-body">
  <p><h1><%= @closet.thing %></h1></p>
  <p><%= image_tag @closet.avatar.url(:medium) %></p>
  <p>Submitted by: <strong><%= link_to @closet.user.username, user_closet_path(id: @closet.user.id) %></strong></p>
</div>

<div class="panel panel-success">
  <div class= "panel-heading">
    Let us know what you think!
  </div>
  <div class="panel-body">
  <%= render 'comments/form' %>
  </div>
</div>
<div class="panel panel-default">
  <div class="panel-header">
    <h4>Comments</h4>
  </div>
  <% @closet.comments.each do |comment| %>
  <div class="panel-body">
    <p>By: <strong><%= link_to comment.user.username, user_closet_path(id: comment.user.id) %></strong></p>
    <p>Rating: <%= comment.rating %></p>  
  </div>
  <% end %>
</div>
<% if current_user.id == @closet.user.id %>
    <p>
    <div class="panel-footer">
    <%= link_to 'Edit', edit_closet_path(@closet), class: "btn btn-warning" %>
    <%= link_to 'Destroy', @closet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
    </div>
    </p>
<% end %>
</div>

app/views/closets/user_closet.html.erb
<h1><%= @user.username %>'s Closet</h1>
<div class="row">
    <p><strong>Birthday:</strong> <%= @user.birthday.strftime("%m/%d/%Y") %></p>
<% current_user.closets.each do |closet| %>
  <div class="col-md-6">
    <div class="panel-body">
    <%= link_to closet.thing, closet %>
    <p> Submitted by: <strong><%= closet.user.username %></strong></p>
  </div>
  <div class="panel-footer">
    <%= link_to 'Show', closet, class: "btn btn-primary" %>
    <%= link_to 'Edit', edit_closet_path(closet), class: "btn btn-warning" %>
    <%= link_to 'Destroy', closet, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
  </div>
  </div>
  <% end %>
 </div>

app/views/closets/your_closet.html.erb
<div class="container">
<div class="row">
<% current_user.closets.each do |closet| %>
  <div class="col-md-6">
    <div class="panel-body">
    <%= link_to closet.thing, closet %>
    <p><%= image_tag closet.avatar.url(:medium) %></p>
    <p> Submitted by: <strong><%= closet.user.username %></strong></p>
    <p><%= link_to 'Edit', edit_closet_path(closet) %> |
    <%= link_to 'Destroy', closet, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  </div>
  <% end %>
  </div>
</div>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field cant-see-me">
    <%= f.number_field :closet_id, value: @closet.id %>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Rating</th>
      <th>Thing</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user.email %></td>
        <td><%= comment.rating %></td>
        <td><%= comment.thing_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.user.email %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @comment.rating %>
</p>

<p>
  <strong>Thing:</strong>
  <%= @comment.thing_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/fashion/closet.html.erb
<div class="container">
<h1>Welcome to Your Closet</h1>
<p>Use the navigation bar to check out all the items in world's closet, as well as your own!</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Closet App</title>
  <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
   <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
</head>
<body>
  <nav class="navbar navbar-default">
  <% if user_signed_in? %>
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="https://fashion-cbwillis06.c9users.io/closets">All Closets</a>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Your Closet", your_closet_path %></li>
      <li><%= link_to "New Item", new_closet_path %></li>
    </ul>
    <div class="pull-right">
     <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %> <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
  </div>
    
    </div>
    <% else %>
    <%= link_to "Sign Up", root_path, class: "navbar-brand" %>
    <% end %>
    </nav>

<%= yield %>

</body>
</html>